/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DashboardImport } from "./routes/_dashboard";
import { Route as IndexImport } from "./routes/index";
import { Route as DashboardDashboardIndexImport } from "./routes/_dashboard/dashboard/index";
import { Route as DashboardDashboardIdImport } from "./routes/_dashboard/dashboard/$id";

// Create Virtual Routes

const RegSigninLazyImport = createFileRoute("/reg/signin")();

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const RegSigninLazyRoute = RegSigninLazyImport.update({
  path: "/reg/signin",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/reg/signin.lazy").then((d) => d.Route));

const DashboardDashboardIndexRoute = DashboardDashboardIndexImport.update({
  path: "/dashboard/",
  getParentRoute: () => DashboardRoute,
} as any);

const DashboardDashboardIdRoute = DashboardDashboardIdImport.update({
  path: "/dashboard/$id",
  getParentRoute: () => DashboardRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_dashboard": {
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    "/reg/signin": {
      preLoaderRoute: typeof RegSigninLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/_dashboard/dashboard/$id": {
      preLoaderRoute: typeof DashboardDashboardIdImport;
      parentRoute: typeof DashboardImport;
    };
    "/_dashboard/dashboard/": {
      preLoaderRoute: typeof DashboardDashboardIndexImport;
      parentRoute: typeof DashboardImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DashboardRoute.addChildren([
    DashboardDashboardIdRoute,
    DashboardDashboardIndexRoute,
  ]),
  RegSigninLazyRoute,
]);

/* prettier-ignore-end */
